// Code generated by go generate; DO NOT EDIT.

package cpf_debug

import (
	"fmt"

	definitions "github.com/nacioboi/go_cpf/_definitions"
	"github.com/nacioboi/go_cpf/cpf_options"
)

const c__MAX_INTERVAL_AMOUNT = 1<<16 - 1

var (
	interval_amount     uint16
	interval_count_down uint16
	log_level           int

	output_handler func(int, string) = func(l int, s string) {
		if l <= log_level {
			fmt.Print(s)
		}
	}

	prefix_handler 	    func() string
)

func Set(key cpf_options.T__Option, value interface{}) {
	definitions.SetImplementation(
		key,
		value,
		&interval_amount,
		&interval_count_down,
		c__MAX_INTERVAL_AMOUNT,
		&output_handler,
		&prefix_handler,
		&log_level,
	)
}

func Log(level int, format string, args ...interface{}) {
	definitions.LogImplementation(
	level,
	output_handler,
	prefix_handler,
	&interval_amount,
	&interval_count_down,
	format,
	args...,
	)
}

func Formatted(out *string, format string, args ...interface{}) {
	definitions.FormattedImplementation(out, format, args...)
}
