//go:build !debug
// +build !debug

// Code generated by go generate; DO NOT EDIT.

package cpf_release

import "github.com/nacioboi/go_cpf/cpf_options"

func Set(key cpf_options.T__Option, value interface{}) {}

func Log(level int, format string, args ...interface{}) {}

func Formatted(out *string, format string, args ...interface{}) {}
